[package]
name = "shurale"
version = "0.1.0"
authors = ["rkharisov <rinat@soramitsu.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

